package venom

// TODO: Determine how to best validate Markdown output - Check files and string contains on their contents?
//func TestMarkdownWrite(t *testing.T) {
//	type args struct {
//		outDir string
//		doc    Documentation
//	}
//	tests := []struct {
//		name    string
//		args    args
//		wantErr bool
//	}{
//		{
//			name: "Simple test",
//			args: args{
//				outDir: t.TempDir(),
//				doc: Documentation{
//					GenerationDate:    time.Now().Format("2-Jan-2006"),
//					AutoGenerationTag: "Auto-generated by test: Simple test",
//					RootCommand: NewCommandFromCobra(&cobra.Command{
//						Use:     "example",
//						Long:    "An example command demonstrating the markdown outputs",
//						Example: "./example --help",
//						RunE: func(cmd *cobra.Command, args []string) error {
//							return nil
//						},
//					},
//						NewOptions(),
//					),
//				},
//			},
//		},
//	}
//	for _, tt := range tests {
//		t.Run(tt.name, func(t *testing.T) {
//			if err := writeMarkdown(tt.args.outDir, tt.args.doc, NewOptions().TemplateOptions()); (err != nil) != tt.wantErr {
//				t.Errorf("writeMarkdown() error = %v, wantErr %v", err, tt.wantErr)
//			}
//		})
//	}
//}
